In [1]:
#1. Why does this feature selection with chi2 fail?
from sklearn.feature_selection import SelectKBest, chi2
from sklearn.preprocessing import MinMaxScaler


# 1. Fixed Syntax Error
X = [[-1, 2, 3], [4, 0, -6], [7, 8, 9], [1, 2, 3]]
y = [0, 1, 0, 1]

# 2. Make data non-negative for chi2
scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X)

# Now run SelectKBest
selector = SelectKBest(score_func=chi2, k=2)
X_new = selector.fit_transform(X_scaled, y)
print("Selected features:\n", X_new)


Selected features:
 [[0.25 0.6 ]
 [0.   0.  ]
 [1.   1.  ]
 [0.25 0.6 ]]


In [2]:
#2.
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import CountVectorizer

user1 = ['action', 'comedy', 'romance']
user2 = ['action', 'thriller', 'comedy']
#convert to binary for user1 and user2
# for user1 action -1,comedy - 1,romance -1,thriller -0
# for user2 action -1, comedy - 1,romance -0, thriller -1
user1 = [1,1,1,0]
user2 = [1,1,0,1]
similarity = cosine_similarity([user1], [user2])
print(similarity)


[[0.66666667]]


In [3]:
#3.
from sklearn.decomposition import PCA

X = [[1, 2], [3, 4], [5, 6]]
# pca = PCA(n_components=5)  # more components than features
pca = PCA(n_components=2)  # since it has only 2 features n_components should be <= 2
X_new = pca.fit_transform(X)
print(X_new)


[[-2.82842712e+00 -4.74426853e-17]
 [ 0.00000000e+00 -0.00000000e+00]
 [ 2.82842712e+00 -4.74426853e-17]]


In [4]:
#4.
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np
from sklearn.impute import SimpleImputer

ratings = np.array([[5, 3, np.nan], [4, np.nan, 3]])
imputer = SimpleImputer()
mean_filled = imputer.fit_transform(ratings) #filling NAN with mean value
print(mean_filled)
zero_filled = np.nan_to_num(ratings) # filling NAN with 0 value
print(zero_filled)
similarity = cosine_similarity(zero_filled)
print(similarity)
similarity = cosine_similarity(mean_filled)
print(similarity)

[[5. 3. 3.]
 [4. 3. 3.]]
[[5. 3. 0.]
 [4. 0. 3.]]
[[1.         0.68599434]
 [0.68599434 1.        ]]
[[1.         0.99382498]
 [0.99382498 1.        ]]


In [5]:
#5.
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression

X = [[2,4,6], [89,190,12], [14,160,18], [20, 30, 40]]
y = [0,1,0,1]

selector = RFE(estimator=LogisticRegression(), n_features_to_select=3)
selector.fit(X, y)  # Error: X and y not defined
print(selector.support_)

[ True  True  True]


In [7]:
#6.
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import TfidfVectorizer

items = ["action movie", "romantic comedy", "sci-fi thriller"]
vectorizer = TfidfVectorizer()
tfidf_matrix = vectorizer.fit_transform(items)
print(tfidf_matrix)
similarity = cosine_similarity(tfidf_matrix[0:1], tfidf_matrix[1:2])
print(similarity)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 7 stored elements and shape (3, 7)>
  Coords	Values
  (0, 0)	0.7071067811865476
  (0, 3)	0.7071067811865476
  (1, 4)	0.7071067811865476
  (1, 1)	0.7071067811865476
  (2, 5)	0.5773502691896257
  (2, 2)	0.5773502691896257
  (2, 6)	0.5773502691896257
[[0.]]


In [8]:
#7.
from sklearn.feature_selection import SelectKBest, f_classif

X = [[1, 2], [3, 4], [5, 6]]
y = [0, 1,1]  # Error: mismatched dimensions
selector = SelectKBest(score_func=f_classif, k=1)
X_new = selector.fit_transform(X, y)
print(X_new)


[[2]
 [4]
 [6]]


In [9]:
#8.
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

ratings = np.array([[5, 4, 3]])
# ratings = np.array([5, 4, 3]).reshape(1, -1)
cosine_similarity(ratings, ratings)


array([[1.]])

In [10]:
#9.
from sklearn.pipeline import Pipeline
from sklearn.feature_selection import SelectKBest, chi2
from sklearn.impute import SimpleImputer

X = [[1, 2], [3, None], [4, 5]]
y = [0, 1, 0]
imputer = SimpleImputer()
X = imputer.fit_transform(X)
print(X)
pipeline = Pipeline([('select', SelectKBest(score_func=chi2, k=1))])

pipeline1 = pipeline.fit(X, y)
print(pipeline1)

print(pipeline1.n_features_in_)


[[1.  2. ]
 [3.  3.5]
 [4.  5. ]]
Pipeline(steps=[('select',
                 SelectKBest(k=1,
                             score_func=<function chi2 at 0x000001C65597A980>))])
2


In [12]:
#10.
from scipy.sparse import csr_matrix
from sklearn.feature_selection import SelectKBest, chi2
from sklearn.preprocessing import MinMaxScaler

X = [[0, -1, 3], [0, 2, 1], [3, -1, 0]]
y = [0, 1, 0]
scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X)
selector = SelectKBest(score_func=chi2, k=2)
X_new = selector.fit_transform(X_scaled, y)
print(X_new)

[[0. 0.]
 [0. 1.]
 [1. 0.]]
